apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-frontend
  labels:
    app: todoapp-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todoapp-frontend
  template:
    metadata:
      labels:
        app: todoapp-frontend
    spec:
      containers:
      - name: todoapp-frontend
        image: 273543149/todoapp-frontend:latest
        ports:
        - containerPort: 8080